name: docker
on:
  push:
    branches: [master, parachain]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v16
        with:
          install_url: https://releases.nixos.org/nix/nix-2.6.0/install
      - uses: cachix/cachix-action@v10
        with:
          name: centrifuge-chain
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Login to Docker Hub
        uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build Docker image
        run: nix build -L .#dockerImage
      - name: List images
        run: docker images
      - name: Push image to Docker Hub
        run: docker push --all-tags --quiet centrifugeio/centrifuge-chain
